### ISSUE TITLE
From RDCMan I don't see compute engines that have been created using an old Windows image (guestOSFeatures are missing)

### ISSUE THREAD

**Issue by informajojo** [GoogleCloudPlatform/iap-windows-rdc-plugin#22]
Hi, trying out the plugin I found that it only found one of my 10-20 servers in each project.
I suspect that the plugin matches the image name to "windows" or something like that, is that correct? I get the servers created from scratch but not the ones that have been created from a (custom) image not starting with the name "windows".

**Comment by jpassing** [comment]
The plugin filters by [Guest OS features](https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images#guest-os-features) - see [source code](https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/blob/1.0.6/Plugin.Google.CloudIap/Integration/ComputeEngineAdapter.cs#L170).

How did you create the your custom images? Are they derived from the public images or imported?

**Comment by informajojo** [comment]
Hi the are derived, done like this:
1. Create WIndows 2012 Server from scratch
2. Set it up with our applications etc
3. Clone it as image1
4. Did some modifications
5. Cloned again as image2
6. Deleted image1

**Comment by jpassing** [comment]
I guess by _cloning_ you mean creating a disk snapshot and creating a new disk/instance from it? 

I just did a quick test and cloned a disk of an existing instance this way. Here's the original disk:
```
    {
      "id": "5338154643258136091",
      "creationTimestamp": "2019-07-15T23:04:37.431-07:00",
      "name": "wdt",
      ...
      "licenses": [
        "https://www.googleapis.com/compute/v1/projects/windows-cloud/global/licenses/windows-server-2019-dc"
      ],
      "guestOsFeatures": [
        {
          "type": "VIRTIO_SCSI_MULTIQUEUE"
        },
        {
          "type": "MULTI_IP_SUBNET"
        },
        {
          "type": "WINDOWS"
        }
      ],
      ...
    }
```

(note the `WINDOWS` in `guestOsFeatures`)

And here's the clone:

```
    {
      "id": "7172692040468719784",
      ...
      "licenses": [
        "https://www.googleapis.com/compute/v1/projects/windows-cloud/global/licenses/windows-server-2019-dc"
      ],
      "guestOsFeatures": [
        {
          "type": "VIRTIO_SCSI_MULTIQUEUE"
        },
        {
          "type": "MULTI_IP_SUBNET"
        },
        {
          "type": "WINDOWS"
        }
      ],
      ...
    },
```

The guestOsFeatures are properly preserved.

The only explanation I could think of is that your original disk might be old enough that it does not have the WINDOWS guestOsFeatures. In this case, you might also not see the **RDP** button in the Cloud Console. 

Could that be possible?

What I could do is relax the filter so that it not only checks for guestOsFeatures, but also for licenses (which is the old way of designating disks as using Windows).

**Comment by informajojo** [comment]
Hi I create a new server using this command:
gcloud compute instances create "[System ID]" --zone "[Zone]" --machine-type "[MACHINE-TYPE]" --maintenance-policy "MIGRATE" --scopes=https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/devstorage.read_write --tags "http-server","https-server" --image "https://www.googleapis.com/compute/v1/projects/myprojectxxx/global/images/**ccimage**" --boot-disk-size "80" --boot-disk-type "pd-ssd" --boot-disk-device-name "[System ID]"

So this image was created from a disk originally yes.
![image](https://user-images.githubusercontent.com/11977031/68479424-3b009f80-022a-11ea-84e6-a6a261ce8cfd.png)
Google console doesnt provide a lot of information...

**Comment by jpassing** [comment]
I used the API to get these details, but you can also run `gcloud compute instances describe [name] --zone [zone]` , then check the `disks` section.

Ex:
```
disks:
- autoDelete: true
  boot: true
  deviceName: wdt
  guestOsFeatures:
  - type: VIRTIO_SCSI_MULTIQUEUE
  - type: MULTI_IP_SUBNET
  - type: WINDOWS
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/windows-cloud/global/licenses/windows-server-2019-dc
```

**Comment by informajojo** [comment]
Ok thanks this is what I get
[example.txt](https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/files/3824819/example.txt)

So yes, I get attachedDisk as kind, not windows.

**Comment by informajojo** [comment]
and guestOsFeatures is missing..

**Comment by informajojo** [comment]
And just to confirm, this comes originally from a fairly old Windows image. So I guess that is the root cause. Not sure if you could potentially filter on license instead. Anyway... for new servers this wont be an issue then.

**Comment by jpassing** [comment]
Thanks -- indeed, the guest OS feature is missing, but the license is there.

I just created https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/issues/22 to change the filtering logic to also consider licenses.

Thanks for surfacing this issue. I was always testing with newer images, so I never ran into this.

**Comment by informajojo** [comment]
OK that is great, thanks

**Comment by jpassing** [comment]
Fixed in https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.21

**Comment by informajojo** [comment]
Sorry but after having installed 1.1.21 I get this instead when refreshing my project:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Google.Solutions.CloudIap.Plugin.Gui.PluginEventHandler.<>c.<OnLoadServersClick>b__10_3(Instance i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at Google.Solutions.CloudIap.Plugin.Gui.PluginEventHandler.<>c__DisplayClass10_0.<OnLoadServersClick>b__2(IEnumerable`1 allInstances)
   at Google.Solutions.CloudIap.Plugin.Gui.WaitDialog.<>c__DisplayClass13_2`1.<Run>b__1()

**Comment by jpassing** [comment]
Aww, sorry about that -- I missed to check for instances with disks without license. Could you try again with https://github.com/GoogleCloudPlatform/iap-windows-rdc-plugin/releases/tag/1.1.22, please?

**Comment by informajojo** [comment]
Thanks, now it works! Actually, it also lists a cpl of Linux dists but for me this is not a problem.
My main driver for this is that I want to close down direct RDP to the compute engines (so that if  an employee quits he will have no access to the server). This helps a lot with achieving this without the hassle of manually setting up SSL tunnels, fix IP addresses etc.

**Comment by jpassing** [comment]
Great, thank you for verifying!
